# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewTest(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 247, 201);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 150, 721, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.qwestionEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.qwestionEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.qwestionEdit.setObjectName("qwestionEdit")
        self.horizontalLayout.addWidget(self.qwestionEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.answerEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.answerEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.answerEdit.setObjectName("answerEdit")
        self.horizontalLayout_2.addWidget(self.answerEdit)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(170, 290, 441, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addAnsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.addAnsButton.setStyleSheet("background-color: rgb(255, 253, 174);\n"
"border-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.addAnsButton.setObjectName("addAnsButton")
        self.horizontalLayout_3.addWidget(self.addAnsButton)
        self.cleaButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.cleaButton.setStyleSheet("background-color: rgb(255, 253, 174);\n"
"border-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.cleaButton.setObjectName("cleaButton")
        self.horizontalLayout_3.addWidget(self.cleaButton)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(490, 399, 281, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.codeEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.codeEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.codeEdit.setObjectName("codeEdit")
        self.horizontalLayout_4.addWidget(self.codeEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 0, 141, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 253, 174);\n"
"border-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 500, 161, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 253, 174);\n"
"border-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.loadButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(474, 500, 131, 41))
        self.loadButton.setStyleSheet("background-color: rgb(255, 253, 174);\n"
"border-color: rgb(255, 255, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.loadButton.setObjectName("loadButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Создание проверочной"))
        self.label_2.setText(_translate("MainWindow", "Вопрос"))
        self.label_3.setText(_translate("MainWindow", "Ответ"))
        self.addAnsButton.setText(_translate("MainWindow", "Добавить вопрос"))
        self.cleaButton.setText(_translate("MainWindow", "Стереть"))
        self.label_4.setText(_translate("MainWindow", "Код проверочной"))
        self.pushButton.setText(_translate("MainWindow", "<---   Вернуться"))
        self.pushButton_2.setText(_translate("MainWindow", "Узнать результаты"))
        self.loadButton.setText(_translate("MainWindow", "Загрузить"))
