# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/* General Settings */\n"
"QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 14px;\n"
"    color: #2c3e50; /* Dark blue for text */\n"
"    background-color: #ecf0f1; /* Light gray background */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #3498db; /* Blue */\n"
"    color: white;\n"
"    border: 1px solid #2980b9; /* Darker blue */\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Darker blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5980; /* Even darker blue when pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7; /* Gray */\n"
"    color: #7f8c8d; /* Light gray text */\n"
"    border: 1px solid #95a5a6;\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7; /* Light gray border */\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #3498db; /* Blue border when focused */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #2c3e50; /* Dark blue */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for titles */\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left: 1px solid #bdc3c7;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    selection-background-color: #3498db; /* Blue for selected item */\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Check Boxes */\n"
"QCheckBox {\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icons/unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Radio Buttons */\n"
"QRadioButton {\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/icons/radio_checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/icons/radio_unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    background-color: #bdc3c7;\n"
"    border: 1px solid #95a5a6;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #3498db; /* Blue */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #bdc3c7;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/icons/up_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for group box titles */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-bottom: none;\n"
"    padding: 8px 16px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    border-bottom: 1px solid white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #3498db; /* Blue on hover */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:horizontal, QScrollBar:vertical {\n"
"    background-color: #ecf0f1;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background-color: #3498db; /* Blue */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tool Tips */\n"
"QToolTip {\n"
"    background-color: #3498db; /* Blue */\n"
"    color: white;\n"
"    border: 1px solid #2980b9;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #3498db; /* Blue */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #3498db; /* Blue */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Tables */\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #3498db; /* Blue */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 1px solid #3498db; /* Blue */\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #ecf0f1;\n"
"    border-top: 1px solid #bdc3c7;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Tool Bars */\n"
"QToolBar {\n"
"    background-color: #ecf0f1;\n"
"    border-bottom: 1px solid #bdc3c7;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #bdc3c7;\n"
"    width: 1px;\n"
"    margin: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.registration_button = QtWidgets.QPushButton(self.centralwidget)
        self.registration_button.setGeometry(QtCore.QRect(280, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.registration_button.setFont(font)
        self.registration_button.setAutoFillBackground(False)
        self.registration_button.setStyleSheet("")
        self.registration_button.setObjectName("registration_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(340, 30, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 120, 431, 266))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 0, 0, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.loginEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.loginEdit.setStyleSheet("")
        self.loginEdit.setObjectName("loginEdit")
        self.gridLayout.addWidget(self.loginEdit, 0, 1, 1, 1)
        self.password1Edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password1Edit.setStyleSheet("")
        self.password1Edit.setObjectName("password1Edit")
        self.gridLayout.addWidget(self.password1Edit, 2, 1, 1, 1)
        self.password2Edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password2Edit.setStyleSheet("")
        self.password2Edit.setObjectName("password2Edit")
        self.gridLayout.addWidget(self.password2Edit, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.usernameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameEdit.setStyleSheet("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registration_button.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_4.setText(_translate("MainWindow", "Регистрация"))
        self.label_3.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "Повторите пароль"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Ученик"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Учитель"))
        self.label_5.setText(_translate("MainWindow", "Выберите роль"))
        self.label_6.setText(_translate("MainWindow", "Имя пользователя"))
        self.pushButton.setText(_translate("MainWindow", "<---   Вернуться"))
