# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tester(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 253, 174);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 247, 201);\n"
"color: rgb(202, 8, 255);")
        self.label.setObjectName("label")
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(604, 502, 161, 31))
        self.endButton.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"gridline-color: rgb(170, 0, 0);")
        self.endButton.setObjectName("endButton")
        self.qwestionText = QtWidgets.QTextBrowser(self.centralwidget)
        self.qwestionText.setEnabled(False)
        self.qwestionText.setGeometry(QtCore.QRect(60, 80, 661, 201))
        self.qwestionText.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.qwestionText.setObjectName("qwestionText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 300, 301, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.answerEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.answerEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 0, 0);")
        self.answerEdit.setObjectName("answerEdit")
        self.horizontalLayout.addWidget(self.answerEdit)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(370, 350, 131, 31))
        self.saveButton.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"gridline-color: rgb(170, 0, 0);")
        self.saveButton.setObjectName("saveButton")
        self.previewButton = QtWidgets.QPushButton(self.centralwidget)
        self.previewButton.setGeometry(QtCore.QRect(30, 422, 171, 31))
        self.previewButton.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"gridline-color: rgb(170, 0, 0);")
        self.previewButton.setObjectName("previewButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(590, 420, 181, 31))
        self.nextButton.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"gridline-color: rgb(170, 0, 0);")
        self.nextButton.setObjectName("nextButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 22, 231, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"gridline-color: rgb(170, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Форма решения задач"))
        self.endButton.setText(_translate("MainWindow", "Завершить работу"))
        self.label_2.setText(_translate("MainWindow", "Ответ"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить ответ"))
        self.previewButton.setText(_translate("MainWindow", "Предыдущий вопрос"))
        self.nextButton.setText(_translate("MainWindow", "Следующий вопрос"))
        self.pushButton.setText(_translate("MainWindow", "<--- Вернуться и бросить всё"))
