# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, label1):
        label1.setObjectName("label1")
        label1.resize(793, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label1.sizePolicy().hasHeightForWidth())
        label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        label1.setFont(font)
        label1.setStyleSheet("/* General Settings */\n"
"QWidget {\n"
"    font-family: \"Comic Sans MS\"; /* Fun and playful font */\n"
"    font-size: 14px;\n"
"    color: #2c3e50; /* Dark blue for text */\n"
"    background-color: #f9f9f9; /* Light gray background */\n"
"}\n"
"\n"
"/* Background Images for Different Pages */\n"
"QWidget#mathPage {\n"
"    background-image: url(:/backgrounds/math_background.png); /* Math-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#sciencePage {\n"
"    background-image: url(:/backgrounds/science_background.png); /* Science-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#literaturePage {\n"
"    background-image: url(:/backgrounds/literature_background.png); /* Literature-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#historyPage {\n"
"    background-image: url(:/backgrounds/history_background.png); /* History-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"    border: 2px solid #ff3b2f; /* Darker coral */\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff3b2f; /* Darker coral on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff1a1a; /* Even darker coral when pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7; /* Gray */\n"
"    color: #7f8c8d; /* Light gray text */\n"
"    border: 2px solid #95a5a6;\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff6f61; /* Coral border when focused */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #2c3e50; /* Dark blue */\n"
"    font-size: 14px;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for titles */\n"
"    background-color: transparent; /* No background for titles */\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #3498db;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    selection-background-color: #ff6f61; /* Coral for selected item */\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Check Boxes */\n"
"QCheckBox {\n"
"    color: #2c3e50;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icons/unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Radio Buttons */\n"
"QRadioButton {\n"
"    color: #2c3e50;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/icons/radio_checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/icons/radio_unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    background-color: #bdc3c7;\n"
"    border: 2px solid #95a5a6;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #3498db;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/icons/up_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for group box titles */\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ecf0f1;\n"
"    border: 2px solid #3498db;\n"
"    border-bottom: none;\n"
"    padding: 10px 20px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    border-bottom: 2px solid white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #ff6f61; /* Coral on hover */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:horizontal, QScrollBar:vertical {\n"
"    background-color: #ecf0f1;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tool Tips */\n"
"QToolTip {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"    border: 2px solid #ff3b2f;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Tables */\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #ff6f61; /* Coral */\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #ecf0f1;\n"
"    border-top: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Tool Bars */\n"
"QToolBar {\n"
"    background-color: #ecf0f1;\n"
"    border-bottom: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #3498db;\n"
"    width: 2px;\n"
"    margin: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(label1)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(140, 30, 511, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 195, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 195, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 62, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.lineEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.log_in = QtWidgets.QPushButton(self.centralwidget)
        self.log_in.setGeometry(QtCore.QRect(300, 170, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.log_in.setFont(font)
        self.log_in.setStyleSheet("")
        self.log_in.setObjectName("log_in")
        self.registration = QtWidgets.QPushButton(self.centralwidget)
        self.registration.setGeometry(QtCore.QRect(300, 260, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.registration.setFont(font)
        self.registration.setStyleSheet("")
        self.registration.setObjectName("registration")
        label1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(label1)
        self.statusbar.setObjectName("statusbar")
        label1.setStatusBar(self.statusbar)

        self.retranslateUi(label1)
        QtCore.QMetaObject.connectSlotsByName(label1)

    def retranslateUi(self, label1):
        _translate = QtCore.QCoreApplication.translate
        label1.setWindowTitle(_translate("label1", "MainWindow"))
        self.lineEdit.setText(_translate("label1", "TESTIFY"))
        self.log_in.setText(_translate("label1", "Вход"))
        self.registration.setText(_translate("label1", "Регистрация"))
