# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tester(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 600)
        MainWindow.setToolTipDuration(-2)
        MainWindow.setStyleSheet("/* General Settings */\n"
"QWidget {\n"
"    font-family: \"Comic Sans MS\"; /* Fun and playful font */\n"
"    font-size: 14px;\n"
"    color: #2c3e50; /* Dark blue for text */\n"
"    background-color: #f9f9f9; /* Light gray background */\n"
"}\n"
"\n"
"/* Background Images for Different Pages */\n"
"QWidget#mathPage {\n"
"    background-image: url(:/backgrounds/math_background.png); /* Math-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#sciencePage {\n"
"    background-image: url(:/backgrounds/science_background.png); /* Science-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#literaturePage {\n"
"    background-image: url(:/backgrounds/literature_background.png); /* Literature-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"QWidget#historyPage {\n"
"    background-image: url(:/backgrounds/history_background.png); /* History-themed background */\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"    border: 2px solid #ff3b2f; /* Darker coral */\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff3b2f; /* Darker coral on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff1a1a; /* Even darker coral when pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #bdc3c7; /* Gray */\n"
"    color: #7f8c8d; /* Light gray text */\n"
"    border: 2px solid #95a5a6;\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff6f61; /* Coral border when focused */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #2c3e50; /* Dark blue */\n"
"    font-size: 14px;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for titles */\n"
"    background-color: transparent; /* No background for titles */\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #3498db;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    selection-background-color: #ff6f61; /* Coral for selected item */\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Check Boxes */\n"
"QCheckBox {\n"
"    color: #2c3e50;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icons/unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Radio Buttons */\n"
"QRadioButton {\n"
"    color: #2c3e50;\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/icons/radio_checked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/icons/radio_unchecked.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    background-color: #bdc3c7;\n"
"    border: 2px solid #95a5a6;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #3498db;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/icons/up_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png); /* Replace with your icon */\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    font-weight: bold;\n"
"    color: #3498db; /* Blue for group box titles */\n"
"    background-color: rgba(255, 255, 255, 0.8); /* Semi-transparent white */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #3498db; /* Blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ecf0f1;\n"
"    border: 2px solid #3498db;\n"
"    border-bottom: none;\n"
"    padding: 10px 20px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    border-bottom: 2px solid white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #ff6f61; /* Coral on hover */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:horizontal, QScrollBar:vertical {\n"
"    background-color: #ecf0f1;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Tool Tips */\n"
"QToolTip {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"    border: 2px solid #ff3b2f;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Tables */\n"
"QTableView {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ff6f61; /* Coral */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Text Edit */\n"
"QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0.9); /* Semi-transparent white */\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #ff6f61; /* Coral */\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #ecf0f1;\n"
"    border-top: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Tool Bars */\n"
"QToolBar {\n"
"    background-color: #ecf0f1;\n"
"    border-bottom: 2px solid #3498db;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #3498db;\n"
"    width: 2px;\n"
"    margin: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qwestionText = QtWidgets.QTextBrowser(self.centralwidget)
        self.qwestionText.setEnabled(False)
        self.qwestionText.setGeometry(QtCore.QRect(60, 80, 351, 201))
        self.qwestionText.setStyleSheet("")
        self.qwestionText.setObjectName("qwestionText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 300, 301, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 14px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.answerEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.answerEdit.setStyleSheet("")
        self.answerEdit.setObjectName("answerEdit")
        self.horizontalLayout.addWidget(self.answerEdit)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(370, 350, 191, 41))
        self.saveButton.setStyleSheet("")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 400, 680, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(270)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previewButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.previewButton.setStyleSheet("")
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout_2.addWidget(self.previewButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.nextButton.setStyleSheet("")
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 792, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font-size: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.endButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.endButton.setStyleSheet("")
        self.endButton.setObjectName("endButton")
        self.horizontalLayout_3.addWidget(self.endButton)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 80, 321, 201))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ответ"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить ответ"))
        self.previewButton.setText(_translate("MainWindow", "Предыдущий вопрос"))
        self.nextButton.setText(_translate("MainWindow", "Следующий вопрос"))
        self.pushButton.setText(_translate("MainWindow", "<--- Вернуться"))
        self.label.setText(_translate("MainWindow", "Форма решения задач"))
        self.endButton.setText(_translate("MainWindow", "Завершить работу"))
